In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import ast

In [2]:
df = pd.read_csv("Movie_Dataset.csv", low_memory=False)

In [3]:
df.head(5)

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [4]:
df.shape

(45466, 24)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  object
 1   belongs_to_collection  4494 non-null   object
 2   budget                 45466 non-null  object
 3   genres                 45466 non-null  object
 4   homepage               7782 non-null   object
 5   id                     45466 non-null  object
 6   imdb_id                45449 non-null  object
 7   original_language      45455 non-null  object
 8   original_title         45466 non-null  object
 9   overview               44512 non-null  object
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  object
 12  production_companies   45463 non-null  object
 13  production_countries   45463 non-null  object
 14  release_date           45379 non-null  object
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(20)
memory usage: 8.3+ MB

In [6]:
df.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [7]:
df.isnull().sum()

adult                        0
belongs_to_collection    40972
budget                       0
genres                       0
homepage                 37684
id                           0
imdb_id                     17
original_language           11
original_title               0
overview                   954
popularity                   5
poster_path                386
production_companies         3
production_countries         3
release_date                87
revenue                      6
runtime                    263
spoken_languages             6
status                      87
tagline                  25054
title                        6
video                        6
vote_average                 6
vote_count                   6
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(17)

In [9]:
df = df.drop_duplicates().reset_index(drop = True)

In [10]:
cols = [
    "title",
    "overview",
    "genres",
    "tagline",
    "belongs_to_collection",
    "production_companies",
    "vote_average",
    "vote_count",
    "release_date",
    "runtime",
    "original_language"
]

In [11]:
df = df[cols]

In [12]:
df.head()

,title,overview,genres,tagline,belongs_to_collection,production_companies,vote_average,vote_count,release_date,runtime,original_language
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...","[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",NaN,"{'id': 10194, 'name': 'Toy Story Collection', ...","[{'name': 'Pixar Animation Studios', 'id': 3}]",7.7,5415.0,1995-10-30,81.0,en
1,Jumanji,When siblings Judy and Peter discover an encha...,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",Roll the dice and unleash the excitement!,NaN,"[{'name': 'TriStar Pictures', 'id': 559}, {'na...",6.9,2413.0,1995-12-15,104.0,en
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",Still Yelling. Still Fighting. Still Ready for...,"{'id': 119050, 'name': 'Grumpy Old Men Collect...","[{'name': 'Warner Bros.', 'id': 6194}, {'name'...",6.5,92.0,1995-12-22,101.0,en
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...","[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",Friends are the people who let you be yourself...,NaN,[{'name': 'Twentieth Century Fox Film Corporat...,6.1,34.0,1995-12-22,127.0,en
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,"[{'id': 35, 'name': 'Comedy'}]",Just When His World Is Back To Normal... He's ...,"{'id': 96871, 'name': 'Father of the Bride Col...","[{'name': 'Sandollar Productions', 'id': 5842}...",5.7,173.0,1995-02-10,106.0,en

In [13]:
df.isnull().sum()

title                        6
overview                   954
genres                       0
tagline                  25042
belongs_to_collection    40956
production_companies         3
vote_average                 6
vote_count                   6
release_date                87
runtime                    263
original_language           11
dtype: int64

In [14]:
new_cols = [
    "title",
    "genres",
    "overview",
    "tagline",
    "production_companies"
]
df_edited = df[new_cols]

In [15]:
df_edited.isnull().sum()

title                       6
genres                      0
overview                  954
tagline                 25042
production_companies        3
dtype: int64

In [16]:
df_edited = df_edited.dropna(subset = ['title'])

In [17]:
df_edited['overview'] = df_edited['overview'].fillna('')

In [18]:
df_edited.isnull().sum()

title                       0
genres                      0
overview                    0
tagline                 25036
production_companies        0
dtype: int64

In [19]:
df_edited.iloc[0]['genres']

"[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]"

In [20]:
df_edited['genres'] = df['genres'].apply(lambda x : " ".join([i['name'] for i in ast.literal_eval(x)]))

In [21]:
df_edited.head()

,title,genres,overview,tagline,production_companies
0,Toy Story,Animation Comedy Family,"Led by Woody, Andy's toys live happily in his ...",NaN,"[{'name': 'Pixar Animation Studios', 'id': 3}]"
1,Jumanji,Adventure Fantasy Family,When siblings Judy and Peter discover an encha...,Roll the dice and unleash the excitement!,"[{'name': 'TriStar Pictures', 'id': 559}, {'na..."
2,Grumpier Old Men,Romance Comedy,A family wedding reignites the ancient feud be...,Still Yelling. Still Fighting. Still Ready for...,"[{'name': 'Warner Bros.', 'id': 6194}, {'name'..."
3,Waiting to Exhale,Comedy Drama Romance,"Cheated on, mistreated and stepped on, the wom...",Friends are the people who let you be yourself...,[{'name': 'Twentieth Century Fox Film Corporat...
4,Father of the Bride Part II,Comedy,Just when George Banks has recovered from his ...,Just When His World Is Back To Normal... He's ...,"[{'name': 'Sandollar Productions', 'id': 5842}..."

In [22]:
df_edited['tagline'] = df_edited['tagline'].fillna('')

In [23]:
df_edited['production_companies'] = df_edited['production_companies'].apply(lambda x : " ".join([i['name'] for i in ast.literal_eval(x)]))
df_edited['production_companies'] = df_edited['production_companies'].fillna('')

In [24]:
df_edited['production_companies'][0]

'Pixar Animation Studios'

In [25]:
df_edited['tags'] = df_edited["tags"] = (
    df_edited["overview"] + " " +
    df_edited["genres"] + " " +
    df_edited["genres"] + " " +
    df_edited["tagline"] + " " +
    df_edited["tagline"] + " " +
    df_edited["production_companies"]
)

In [26]:
df_edited.head()

,title,genres,overview,tagline,production_companies,tags
0,Toy Story,Animation Comedy Family,"Led by Woody, Andy's toys live happily in his ...",,Pixar Animation Studios,"Led by Woody, Andy's toys live happily in his ..."
1,Jumanji,Adventure Fantasy Family,When siblings Judy and Peter discover an encha...,Roll the dice and unleash the excitement!,TriStar Pictures Teitler Film Interscope Commu...,When siblings Judy and Peter discover an encha...
2,Grumpier Old Men,Romance Comedy,A family wedding reignites the ancient feud be...,Still Yelling. Still Fighting. Still Ready for...,Warner Bros. Lancaster Gate,A family wedding reignites the ancient feud be...
3,Waiting to Exhale,Comedy Drama Romance,"Cheated on, mistreated and stepped on, the wom...",Friends are the people who let you be yourself...,Twentieth Century Fox Film Corporation,"Cheated on, mistreated and stepped on, the wom..."
4,Father of the Bride Part II,Comedy,Just when George Banks has recovered from his ...,Just When His World Is Back To Normal... He's ...,Sandollar Productions Touchstone Pictures,Just when George Banks has recovered from his ...

In [27]:
df_edited['tags'][1]

"When siblings Judy and Peter discover an enchanted board game that opens the door to a magical world, they unwittingly invite Alan -- an adult who's been trapped inside the game for 26 years -- into their living room. Alan's only hope for freedom is to finish the game, which proves risky as all three find themselves running from giant rhinoceroses, evil monkeys and other terrifying creatures. Adventure Fantasy Family Adventure Fantasy Family Roll the dice and unleash the excitement! Roll the dice and unleash the excitement! TriStar Pictures Teitler Film Interscope Communications"

In [28]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize
import re

In [29]:
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ngarg\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\ngarg\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\ngarg\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\ngarg\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [30]:
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

In [31]:
def processtext(text):
    text = str(text).lower()
    text = re.sub(r'[^a-zA-Z\s]' , '' , text)
    words = word_tokenize(text)
    words = [word for word in words if word not in stop_words]

    words = [lemmatizer.lemmatize(word) for word in words]

    return " ".join(words)

df_edited['tags'] = df_edited['tags'].apply(processtext)

In [32]:
df_edited['tags'][1]

'sibling judy peter discover enchanted board game open door magical world unwittingly invite alan adult who trapped inside game year living room alans hope freedom finish game prof risky three find running giant rhinoceros evil monkey terrifying creature adventure fantasy family adventure fantasy family roll dice unleash excitement roll dice unleash excitement tristar picture teitler film interscope communication'

In [33]:
df_edited = df_edited.reset_index(drop = True)

In [34]:
indices = pd.Series(df.index , index = df['title']).drop_duplicates()

In [35]:
indices

title
Toy Story                          0
Jumanji                            1
Grumpier Old Men                   2
Waiting to Exhale                  3
Father of the Bride Part II        4
                               ...
Subdue                         45444
Century of Birthing            45445
Betrayal                       45446
Satan Triumphant               45447
Queerama                       45448
Length: 45449, dtype: int64

In [36]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [37]:
tfidf = TfidfVectorizer(max_features=50000, ngram_range=(1,2) , stop_words='english', min_df=2 , max_df=0.95 , sublinear_tf=True)

In [38]:
tfidf_matrix = tfidf.fit_transform(df_edited['tags'])

In [39]:
tfidf_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1786598 stored elements and shape (45443, 50000)>

In [40]:
from sklearn.metrics.pairwise import cosine_similarity

In [41]:
from sklearn.metrics.pairwise import cosine_similarity

def recommend(title, n=10):
    if title not in indices:
        return "Movie not found."

    idx = indices[title]

    sim_scores = cosine_similarity(
        tfidf_matrix[idx],
        tfidf_matrix
    ).flatten()

    similar_idx = sim_scores.argsort()[::-1][1:101]

    recommendations = df.iloc[similar_idx].copy()

    recommendations["similarity"] = sim_scores[similar_idx]

    recommendations = recommendations[
        (recommendations["vote_count"] >= 50) &
        (recommendations["vote_average"] >= 6)
    ]

    recommendations = recommendations.sort_values(
        by=["similarity", "vote_average"],
        ascending=[False, False]
    )

    return recommendations[
        [
            "title",
            "vote_average",
            "runtime",
            "vote_count",
            "release_date"
        ]
    ].head(n)

In [42]:
recommend("Harry Potter and the Chamber of Secrets")

,title,vote_average,runtime,vote_count,release_date
7724,Harry Potter and the Prisoner of Azkaban,7.7,141.0,6037.0,2004-05-31
16124,Harry Potter and the Deathly Hallows: Part 1,7.5,146.0,5708.0,2010-10-17
10551,Harry Potter and the Goblet of Fire,7.5,157.0,5758.0,2005-11-05
13889,Harry Potter and the Half-Blood Prince,7.4,153.0,5435.0,2009-07-07
11924,Harry Potter and the Order of the Phoenix,7.4,138.0,5633.0,2007-06-28
4765,Harry Potter and the Philosopher's Stone,7.5,152.0,7188.0,2001-11-16
17432,Harry Potter and the Deathly Hallows: Part 2,7.9,130.0,6141.0,2011-07-07
6100,Journey to the Center of the Earth,6.7,132.0,107.0,1959-12-14
5405,Clash of the Titans,6.8,118.0,208.0,1981-03-15
30385,Max,6.8,111.0,282.0,2015-06-26